name = "blogs-do"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[ai]]
binding = "AI"

[[vectorize]]
binding = "BLOG_INDEX"
index_name = "blog-content"

[build]
command = "pnpm run build"
cwd = "."
watch_dir = "src"

[site]
bucket = ".vercel/output/static"

[env.production]
name = "blogs-do-prod"
route = "blogs.do/*"

[env.staging]
name = "blogs-do-staging"
route = "staging.blogs.do/*"
